#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

pgrep -x picom >/dev/null || picom --backend glx --vsync &

xsetroot -cursor_name left_ptr &

~/.config/bspwm/panel.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width 1
bspc config window_gap 0
bspc config split_ratio 0.50
bspc config active_border_color #444444
bspc config focused_border_color #777777
bspc config normal_border_color #222222
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
